/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_termux_shared_file_FileUtils */

#ifndef _Included_com_termux_shared_file_FileUtils
#define _Included_com_termux_shared_file_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_termux_shared_file_FileUtils
 * Method:    readlink
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_termux_shared_file_FileUtils_readlink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_termux_shared_file_FileUtils
 * Method:    symlink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_termux_shared_file_FileUtils_symlink
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
