/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReadlinkTest */

#ifndef _Included_ReadlinkTest
#define _Included_ReadlinkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReadlinkTest
 * Method:    readlink
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ReadlinkTest_readlink
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
