name: Unit tests

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    types:
      - requested
    branches:
      - master
      - android-10
#   push:
#     branches:
#       - master
#       - android-10
  pull_request:
    branches:
      - master
      - android-10

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
    - name: Attach workspace file
        uses: actions/upload-artifact@v3
        with:
          name: termux-app
          path: .
