name: ENV

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Show env
        run: env

      - name: Pack workspace
        run: |
          zip -q -r9 termux-app.zip .
          du -h termux-app.zip