name: ENV

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Show env
        run: env

      - name: Show workspace
        run: |
         ls ${{env.RUNNER_WORKSPACE}}