name: ENV

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Show env
        run: env
        
      - name: Show jni versions
        run: |
          echo $JAVA_HOME
          cat $JAVA_HOME/include/jni.h | grep -i -n jni_version

      - name: Show c++ standard
        run: |
          g++ -dM -E -x c++  /dev/null | grep -F __cplusplus

      - name: Show ucnv
        run:  |
          cd /usr/local/lib/android/sdk/ndk/25.2.9519653
          cat README
          ls -l | grep "^-" | wc -l

      - name: Attach workspace file
        uses: actions/upload-artifact@v3
        with:
          name: termux-app
          path: .
